// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl54i6ObNdrwD6D5lWyEpTxYpUc_QJIyI',
    appId: '1:474652276463:android:cdf423f4db7ae2e3954d1a',
    messagingSenderId: '474652276463',
    projectId: 'app-yaber-test',
    storageBucket: 'app-yaber-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8sx4FQLPxwqnDos6l_Ft-1IG500sOG1c',
    appId: '1:474652276463:ios:3fd51fb891bccf0c954d1a',
    messagingSenderId: '474652276463',
    projectId: 'app-yaber-test',
    storageBucket: 'app-yaber-test.appspot.com',
    androidClientId: '474652276463-p5td13qk58fe01vh2do53m4n628rdrh7.apps.googleusercontent.com',
    iosClientId: '474652276463-ntdfaecjspg1np2a678nlms5039mob7b.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterYaber',
  );
}
